/** Canonical API error codes (align responses, logs, and clients). */
const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  CONFLICT: "CONFLICT",
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  DATABASE_UNAVAILABLE: "DATABASE_UNAVAILABLE",
  NETWORK_ERROR: "NETWORK_ERROR",
};

module.exports = { ERROR_CODES };
