/**
 * Phase 6.5 — canonical stream event type strings (financial pipeline).
 * @readonly
 */
module.exports = {
  // Ingest / idempotency
  TRANSACTION_ACCEPTED: "TRANSACTION_ACCEPTED",
  IDEMPOTENCY_HIT: "IDEMPOTENCY_HIT",
  SALE_QUEUED_OFFLINE: "SALE_QUEUED_OFFLINE",

  // Projection
  LEDGER_LINE_CREATED: "LEDGER_LINE_CREATED",
  STATE_REDUCED: "STATE_REDUCED",

  // Reconciliation
  RECONCILIATION_PASS: "RECONCILIATION_PASS",
  RECONCILIATION_FAIL: "RECONCILIATION_FAIL",
  RECONCILIATION_DEGRADED: "RECONCILIATION_DEGRADED",
  STATE_DRIFT_DETECTED: "STATE_DRIFT_DETECTED",

  // Snapshot
  SNAPSHOT_CREATED: "SNAPSHOT_CREATED",
  SNAPSHOT_REFRESHED: "SNAPSHOT_REFRESHED",
  SNAPSHOT_FALLBACK_USED: "SNAPSHOT_FALLBACK_USED",
};
